# Generated by Django 3.2 on 2023-05-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0003_auto_20230525_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={
                'ordering': ('pub_date',),
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'произведение'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('author', 'title')},
        ),
    ]
